/* eslint-disable */
/* prettier-ignore */
// oxfmt-ignore
// @ts-nocheck
// noinspection ES6UnusedImports
// Generated by vue-router. !! DO NOT MODIFY THIS FILE !!
// It's recommended to commit this file.
// Make sure to add this file to your tsconfig.json file as an "includes" or "files" entry.

import type {
  RouteRecordInfo,
  ParamValue,
  ParamValueOneOrMore,
  ParamValueZeroOrMore,
  ParamValueZeroOrOne,
} from 'vue-router'
import type {
  _ExtractParamParserType,
} from 'vue-router/experimental'

declare module 'vue-router' {
  interface TypesConfig {
    _ParamParsers: {}
    RouteNamedMap: import('vue-router/auto-routes').RouteNamedMap
    _RouteFileInfoMap: import('vue-router/auto-routes')._RouteFileInfoMap
  }
}

declare module 'vue-router/auto-routes' {
  /**
   * Route name map generated by vue-router
   */
  export interface RouteNamedMap {
    '/': RouteRecordInfo<
      '/',
      '/',
      Record<never, never>,
      Record<never, never>,
      | '//(index)'
      | '//acervo/AcervoList'
      | '//dashboard/Dashboard'
      | '//emprestimo/EmprestimoEdit'
      | '//emprestimo/EmprestimoList'
      | '//relatorio/RelatorioList'
      | '//second'
      | '//usuario/UsuarioEdit'
      | '//usuario/UsuarioList'
    >,
    '//(index)': RouteRecordInfo<
      '//(index)',
      '/',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '//acervo/AcervoList': RouteRecordInfo<
      '//acervo/AcervoList',
      '/acervo/AcervoList',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '//dashboard/Dashboard': RouteRecordInfo<
      '//dashboard/Dashboard',
      '/dashboard/Dashboard',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '//emprestimo/EmprestimoEdit': RouteRecordInfo<
      '//emprestimo/EmprestimoEdit',
      '/emprestimo/EmprestimoEdit',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '//emprestimo/EmprestimoList': RouteRecordInfo<
      '//emprestimo/EmprestimoList',
      '/emprestimo/EmprestimoList',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '//relatorio/RelatorioList': RouteRecordInfo<
      '//relatorio/RelatorioList',
      '/relatorio/RelatorioList',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '//second': RouteRecordInfo<
      '//second',
      '/second',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '//usuario/UsuarioEdit': RouteRecordInfo<
      '//usuario/UsuarioEdit',
      '/usuario/UsuarioEdit',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '//usuario/UsuarioList': RouteRecordInfo<
      '//usuario/UsuarioList',
      '/usuario/UsuarioList',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/[...path]': RouteRecordInfo<
      '/[...path]',
      '/:path(.*)',
      { path: ParamValue<true> },
      { path: ParamValue<false> },
      | never
    >,
  }

  /**
   * Route file to route info map by vue-router.
   * Used by the \`sfc-typed-router\` Volar plugin to automatically type \`useRoute()\`.
   *
   * Each key is a file path relative to the project root with 2 properties:
   * - routes: union of route names of the possible routes when in this page (passed to useRoute<...>())
   * - views: names of nested views (can be passed to <RouterView name="...">)
   *
   * @internal
   */
  export interface _RouteFileInfoMap {
    'src/pages/index.vue': {
      routes:
        | '/'
        | '//(index)'
        | '//acervo/AcervoList'
        | '//dashboard/Dashboard'
        | '//emprestimo/EmprestimoEdit'
        | '//emprestimo/EmprestimoList'
        | '//relatorio/RelatorioList'
        | '//second'
        | '//usuario/UsuarioEdit'
        | '//usuario/UsuarioList'
      views:
        | 'default'
      pathParamNames:
        | never
    }
    'src/pages/index/(index).vue': {
      routes:
        | '//(index)'
      views:
        | never
      pathParamNames:
        | never
    }
    'src/pages/index/acervo/AcervoList.vue': {
      routes:
        | '//acervo/AcervoList'
      views:
        | never
      pathParamNames:
        | never
    }
    'src/pages/index/dashboard/Dashboard.vue': {
      routes:
        | '//dashboard/Dashboard'
      views:
        | never
      pathParamNames:
        | never
    }
    'src/pages/index/emprestimo/EmprestimoEdit.vue': {
      routes:
        | '//emprestimo/EmprestimoEdit'
      views:
        | never
      pathParamNames:
        | never
    }
    'src/pages/index/emprestimo/EmprestimoList.vue': {
      routes:
        | '//emprestimo/EmprestimoList'
      views:
        | never
      pathParamNames:
        | never
    }
    'src/pages/index/relatorio/RelatorioList.vue': {
      routes:
        | '//relatorio/RelatorioList'
      views:
        | never
      pathParamNames:
        | never
    }
    'src/pages/index/second.vue': {
      routes:
        | '//second'
      views:
        | never
      pathParamNames:
        | never
    }
    'src/pages/index/usuario/UsuarioEdit.vue': {
      routes:
        | '//usuario/UsuarioEdit'
      views:
        | never
      pathParamNames:
        | never
    }
    'src/pages/index/usuario/UsuarioList.vue': {
      routes:
        | '//usuario/UsuarioList'
      views:
        | never
      pathParamNames:
        | never
    }
    'src/pages/[...path].vue': {
      routes:
        | '/[...path]'
      views:
        | never
      pathParamNames:
        | 'path'
    }
  }

  /**
   * Get a union of possible route names in a certain route component file.
   * Used by the \`sfc-typed-router\` Volar plugin to automatically type \`useRoute()\`.
   *
   * @internal
   */
  export type _RouteNamesForFilePath<FilePath extends string> =
    _RouteFileInfoMap extends Record<FilePath, infer Info>
      ? Info['routes']
      : keyof RouteNamedMap
}

export {}
