/* eslint-disable */
/* prettier-ignore */
// oxfmt-ignore
// @ts-nocheck
// noinspection ES6UnusedImports
// Generated by vue-router. !! DO NOT MODIFY THIS FILE !!
// It's recommended to commit this file.
// Make sure to add this file to your tsconfig.json file as an "includes" or "files" entry.

import type {
  RouteRecordInfo,
  ParamValue,
  ParamValueOneOrMore,
  ParamValueZeroOrMore,
  ParamValueZeroOrOne,
} from 'vue-router'
import type {
  _ExtractParamParserType,
} from 'vue-router/experimental'

declare module 'vue-router' {
  interface TypesConfig {
    _ParamParsers: {}
    RouteNamedMap: import('vue-router/auto-routes').RouteNamedMap
    _RouteFileInfoMap: import('vue-router/auto-routes')._RouteFileInfoMap
  }
}

declare module 'vue-router/auto-routes' {
  /**
   * Route name map generated by vue-router
   */
  export interface RouteNamedMap {
    '/': RouteRecordInfo<
      '/',
      '/',
      Record<never, never>,
      Record<never, never>,
      | '//(index)'
      | '//autor/AutorEdit'
      | '//autor/AutorList'
      | '//categoria/CategoriaEdit'
      | '//categoria/CategoriaList'
      | '//livro/LivroEdit'
      | '//livro/LivroList'
      | '//second'
      | '//usuario/UsuarioEdit'
      | '//usuario/UsuarioList'
    >,
    '//(index)': RouteRecordInfo<
      '//(index)',
      '/',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '//autor/AutorEdit': RouteRecordInfo<
      '//autor/AutorEdit',
      '/autor/AutorEdit',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '//autor/AutorList': RouteRecordInfo<
      '//autor/AutorList',
      '/autor/AutorList',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '//categoria/CategoriaEdit': RouteRecordInfo<
      '//categoria/CategoriaEdit',
      '/categoria/CategoriaEdit',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '//categoria/CategoriaList': RouteRecordInfo<
      '//categoria/CategoriaList',
      '/categoria/CategoriaList',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '//livro/LivroEdit': RouteRecordInfo<
      '//livro/LivroEdit',
      '/livro/LivroEdit',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '//livro/LivroList': RouteRecordInfo<
      '//livro/LivroList',
      '/livro/LivroList',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '//second': RouteRecordInfo<
      '//second',
      '/second',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '//usuario/UsuarioEdit': RouteRecordInfo<
      '//usuario/UsuarioEdit',
      '/usuario/UsuarioEdit',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '//usuario/UsuarioList': RouteRecordInfo<
      '//usuario/UsuarioList',
      '/usuario/UsuarioList',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/[...path]': RouteRecordInfo<
      '/[...path]',
      '/:path(.*)',
      { path: ParamValue<true> },
      { path: ParamValue<false> },
      | never
    >,
  }

  /**
   * Route file to route info map by vue-router.
   * Used by the \`sfc-typed-router\` Volar plugin to automatically type \`useRoute()\`.
   *
   * Each key is a file path relative to the project root with 2 properties:
   * - routes: union of route names of the possible routes when in this page (passed to useRoute<...>())
   * - views: names of nested views (can be passed to <RouterView name="...">)
   *
   * @internal
   */
  export interface _RouteFileInfoMap {
    'src/pages/index.vue': {
      routes:
        | '/'
        | '//(index)'
        | '//autor/AutorEdit'
        | '//autor/AutorList'
        | '//categoria/CategoriaEdit'
        | '//categoria/CategoriaList'
        | '//livro/LivroEdit'
        | '//livro/LivroList'
        | '//second'
        | '//usuario/UsuarioEdit'
        | '//usuario/UsuarioList'
      views:
        | 'default'
      pathParamNames:
        | never
    }
    'src/pages/index/(index).vue': {
      routes:
        | '//(index)'
      views:
        | never
      pathParamNames:
        | never
    }
    'src/pages/index/autor/AutorEdit.vue': {
      routes:
        | '//autor/AutorEdit'
      views:
        | never
      pathParamNames:
        | never
    }
    'src/pages/index/autor/AutorList.vue': {
      routes:
        | '//autor/AutorList'
      views:
        | never
      pathParamNames:
        | never
    }
    'src/pages/index/categoria/CategoriaEdit.vue': {
      routes:
        | '//categoria/CategoriaEdit'
      views:
        | never
      pathParamNames:
        | never
    }
    'src/pages/index/categoria/CategoriaList.vue': {
      routes:
        | '//categoria/CategoriaList'
      views:
        | never
      pathParamNames:
        | never
    }
    'src/pages/index/livro/LivroEdit.vue': {
      routes:
        | '//livro/LivroEdit'
      views:
        | never
      pathParamNames:
        | never
    }
    'src/pages/index/livro/LivroList.vue': {
      routes:
        | '//livro/LivroList'
      views:
        | never
      pathParamNames:
        | never
    }
    'src/pages/index/second.vue': {
      routes:
        | '//second'
      views:
        | never
      pathParamNames:
        | never
    }
    'src/pages/index/usuario/UsuarioEdit.vue': {
      routes:
        | '//usuario/UsuarioEdit'
      views:
        | never
      pathParamNames:
        | never
    }
    'src/pages/index/usuario/UsuarioList.vue': {
      routes:
        | '//usuario/UsuarioList'
      views:
        | never
      pathParamNames:
        | never
    }
    'src/pages/[...path].vue': {
      routes:
        | '/[...path]'
      views:
        | never
      pathParamNames:
        | 'path'
    }
  }

  /**
   * Get a union of possible route names in a certain route component file.
   * Used by the \`sfc-typed-router\` Volar plugin to automatically type \`useRoute()\`.
   *
   * @internal
   */
  export type _RouteNamesForFilePath<FilePath extends string> =
    _RouteFileInfoMap extends Record<FilePath, infer Info>
      ? Info['routes']
      : keyof RouteNamedMap
}

export {}
